---
title: "Cedar Creek data analysis"
subtitle: "Example Graph"
author: "Melissa DeSiervo"
date: "9/22/2021"
output: html_document
---

Example graphing script to get started working with the data.

```{r data backround information}
# Eric Seabloom 25 Sept 2012

# This code reads in data from a long-term nitrogen addition experiment 
# conducted at Cedar Creek LTER, MN, USA. Results of this experiment 
# and detailed overview of studies are in the following:

# Tilman, D. 1987. Secondary succession and the pattern of plant 
# dominance along experimental nitrogen gradients. 
# Ecological Monographs 57:189-214.

# Inouye, R. S., and D. Tilman. 1988. Convergence and divergence of 
# old-field plant communites along experimental nitrogen gradients. 
# Ecology 69:995-1004.

# Further information is available on Cedar Creek LTER Website:
# http://www.cedarcreek.umn.edu/research/experiments/e001.php

# Variable Descriptions
# Year:      Year
# Field:     Field name
# Plot:      Plot number
# Ntrt:      Nitrogen treatment (See Table 1 in Tilman 1987 and Below)
# nadd:      Nitrogen addition (g/m2/yr)
# OtherAdd:  Other nutrients added with N (TRUE or FALSE)

# N Treatments (Ntrt) Details (from Table 1 Tilman 1987)
# Ntrt Trt g N/m2/yr Other nutrients 
# 1     A       0.0      All 
# 2     B       1.0      All 
# 3     C       2.0      All 
# 4     D       3.4      All 
# 5     E       5.4      All 
# 6     F       9.5      All 
# 7     G      17.0      All 
# 8     H      27.2      All 
# 9     I       0.0      None 

# Experiment E001 was intact prior to fertilization treatments, while E002
# was disked prior to fertilization experiments. Details are in Tilman (1987).

# Oldfield Dates of last plowing
# A 1968, 
# B 1957 
# C 1934 
# D Never plowed
```


```{r - packages and libraries}
library(plyr)
library(dplyr)
library(ggplot2)
library(ape)
library(devtools)
library(tidyr)
library(vegan)
library(viridis)
library(stringr)
library(here)
```

# Read in cleaned data

Note this takes several minutes to run.

```{r}
source(here("data_cleaning/cleaning_CC.R"))
```


# Example graph of a spp. abundance over time

```{r - reorganize data for graph}

### this data set (exp12subset_2 has fields ABC, E001 and E002 from 1982-2004) ## > 2004 was a change in the fire regime## ONLY the control, low (1), med(3.4), and high (9.5) nutrient treatments) ##

##wide to long form##

exp12ABC_long <- gather(exp12subset_2, species, biomass, 'mass.above.ACHILLEA MILLEFOLIUM(LANULOSA)':'mass.above.VIOLA SP.', factor_key=TRUE)

##remove extra text##
exp12ABC_long$species<-str_remove(exp12ABC_long$species, "mass.above.")


##make a column for exp_ntrt_year##

exp12ABC_long_2<-exp12ABC_long %>% mutate( expntrtyear_2= paste(exp,ntrt, year, sep = '_'))

exp12ABC_long_3<-exp12ABC_long_2 %>% mutate(expntrt= paste(exp,ntrt, sep = '_')) %>% select(field, plot, disk,year, ntrt, nadd, expntrtyear_2, expntrt, species, biomass)


##sum all species abundance across plots with the same treatment group and year ###includes zeroes!!!#####

sum_allsp_exp12ABC<-exp12ABC_long_3%>% group_by(species, disk,year, ntrt, nadd, expntrtyear_2, expntrt,) %>% dplyr::summarise(sumbiomass=sum(biomass, na.rm=TRUE),n=n())

sum_allsp_exp12ABC<-as.data.frame(sum_allsp_exp12ABC)



```


```{r - graph spp abundance over time}

### this data set (sum_allsp_exp12ABC has the sum of all spp across all fields in each year in each ntrt treatmet (just the 0, low, med, high)##

mytheme<- theme_bw() + 
    theme(axis.line.x= element_line(colour = "black", size=0.3)) + 
    theme(axis.line.y= element_line(colour = "black", size=0.3)) + 
    theme(axis.text.x=element_text(size=8, colour = "black")) + 
    theme(axis.text.y=element_text(size=8, colour = "black")) + 
    theme(axis.title=element_text(size=10)) + 
    theme(plot.title=element_text(size=7)  + 
              theme(plot.title = element_text(hjust = 0.5))) + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

##

sum_allsp_exp12ABC$ntrt<-mapvalues(sum_allsp_exp12ABC$ntrt, from=c("9", "2", "4",  "6"), to=c("Control (0)", "Low (1)", "Med (3.4)", "High (9.5)"))

sum_allsp_exp12ABC$ntrt <- relevel(sum_allsp_exp12ABC$ntrt, "Control (0)")

sum_allsp_exp12ABC$disk<-mapvalues(sum_allsp_exp12ABC$disk, from=c("0", "1"), to=c("Intact in 1982 (E001)", "Disturbed in 1982 (E002)"))


###subset out 1 spp##
ACHMIL_exp12ABC<-subset(sum_allsp_exp12ABC, species=="ACHILLEA MILLEFOLIUM(LANULOSA)")


Sppovertime<-ACHMIL_exp12ABC %>% ggplot(aes(x=as.numeric(year), y=sumbiomass, color=ntrt))+
    geom_point()+
    geom_line()+
    facet_grid(ntrt~disk) + 
    mytheme+
    ylab("Biomass (g)")+
    xlab("Year")+
    ggtitle("Achillea millefolium time series")+
    theme(legend.title = element_blank())+
    theme(legend.key.size = unit(0.5, "cm"))

Sppovertime

```


